### ISSUE TITLE
Theme Adjustments for Going Live

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#23]
@DrDrij here are a few theme adjustments would like your thoughts on before we can go live. They mainly relate to the `landing/title page`. The way `jupuyter-book` works is the first `file` in the `_config.yml` is a special page. 

1. We think the project title should feature prominently and perhaps remove the the `document navigation`/`blue bar` component for this page only. Note this page doesn't have to be called a specific name but if it helps in the short run we can call it `intro`. 

2. For the `title page` we are thinking we will add the contents to the actual content pane and go back to `hide` the `left hand contents pane (by default)` to be a bit more clean for the front page.

3. The `tableofcontents` directive provided by `jupyter-book` for the content pane needs some styling around `caption-text` elements

https://5f766efb6978501643da1ad5--epic-agnesi-957267.netlify.app/intro.html

```html
<span class="caption-text">Introduction to Python</span>
```

**One other item (non title page):**

1. When you collapse the  left hand pane the contents become off center in the page and right hand part of the page gets a lot of white space. Is it possible for the contents pane to get bigger instead and keep the right hand pane where it is?

**Comment by DrDrij** [comment]
I've pushed 2 commits to address the content column centering, left menu position and styles for the caption text.
Is it possible to add a variable or flag on the first page so that we could add some logic to hide the menu and the blue underlined content-header? `if page_home echo 'class="home"'` or the like.

This could then go in the layout.html file to add an additional class to the body element and the rest I can take care of in the CSS file.

@mmcky I hope I didn't mess anything up on this repo - I tried following your instructions to do a rebuild but it failed.

**Comment by mmcky** [comment]
thanks @DrDrij I will trigger rebuilds for you.

**Comment by mmcky** [comment]
thanks @DrDrij all seems to be addressed now except for the `home` adjustments which needs a hook for you to apply

**Comment by mmcky** [comment]
Closing this as title issue is tracked by #22
